theme = "custom"

[editor]
completion-replace = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-progress-messages = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "spacer",
  "diagnostics",
  "file-modification-indicator",
]
right = [
  "version-control",
  "spacer",
  "workspace-diagnostics",
  "selections",
  "primary-selection-length",
  "register",
  "position",
  "position-percentage",
  "spacer",
  "file-type",
  "file-indent-style",
  "file-encoding"
]

[keys.insert]
C-left = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-right = ["move_next_word_start", "move_char_left", "move_char_right"]
C-up = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
C-down = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
S-tab = "goto_prev_tabstop"

[keys.normal]
C-s = ":write"
C-left = "move_prev_word_start"
C-right = "move_next_word_start"
C-up = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
C-down = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]

[keys.select]
C-left = "extend_prev_word_start"
C-right = "extend_next_word_start"
C-up = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
C-down = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]
