[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.gopls.config]
# Do not insert parentheses on completed function calls
completeFunctionCalls = false

[language-server.scls]
command = "simple-completion-language-server"

[language-server.vscode-css-language-server.config]
css.validate.enable = true
format.insertFinalNewline = true
provideFormatter = true

[language-server.vscode-html-language-server.config]
format.endWithNewline = true
provideFormatter = true

[[language]]
name = "go"
language-servers = ["gopls", "scls"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
